# This workflow builds a snap package of development snapshot
      

name: Build snap

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up and run Snapcraft
        uses: snapcore/action-build@v1

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-snap
          path: '*.snap'
