# This workflow builds a snap package of development snapshot
      

name: Build snap

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Snapcraft
        run: |
          sudo snap install lxd
          sudo snap install snapcraft --classic
	  lxd init

      - name: Build Snap
        run: |
          snapcraft

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-snap
          path: '*.snap'
